language: c

compiler:
  - clang
  - gcc

script:
  - make

addons:
  apt:
    packages:
    - libpam0g-dev

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
